language: python
install: skip
os: freebsd 

jobs:
  include:
    - dist: focal
      script:
        - echo "Threads/core $(nproc --all)"
        - free -g
        - python3 hello.py
    - dist: focal
      vm:
        size: medium
      script:
        - echo "Threads/core $(nproc --all)"
        - free -g
    - dist: focal
      vm:
        size: large
      script:
        - echo "Threads/core $(nproc --all)"
        - free -g
    - dist: focal
      vm:
        size: x-large
