language: python
install: skip

jobs:
  include:
    - os: freebsd
      script:
        - uname -mrs
        - freebsd-version
        - sysctl -a hw.model
        - sysctl -a | grep -i hw.*cpu
        - python3 hello.py
    - os: freebsd
      vm:
        size: medium
