language: python
install: skip
os: freebsd 

jobs:
  include:
     - script:
        - uname -mrs
        - freebsd-version
        - sysctl -a hw.model
        - sysctl -a | grep -i hw.*cpu
        - python3 hello.py
      vm:
        size: medium
      script:
        - uname -mrs
        - freebsd-version
        - sysctl -a hw.model
        - sysctl -a | grep -i hw.*cpu
        - python3 hello.py
      vm:
        size: large
      script:
        - uname -mrs
        - freebsd-version
        - sysctl -a hw.model
        - sysctl -a | grep -i hw.*cpu
        - python3 hello.py
      vm:
        size: x-large
