language: python
install: skip
arch: arm64

jobs:
  include:
    - os: freebsd
      script:
        - uname -mrs
        - freebsd-version
        - sysctl -a hw.model
        - sysctl -a | grep -i hw.*cpu
        - chmod u+x python3 hello.py
    - os: freebsd
      vm:
        size: medium
